# Generated by Django 5.0 on 2026-06-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('group', models.CharField(max_length=100, verbose_name='Группа')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Оценка от 1 до 100', null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к оценке'),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оценено'),
        ),
    ]
