# Generated by Django 5.0 on 2026-06-11 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_student_submission_grade_submission_grade_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название задания')),
                ('source_text', models.TextField(blank=True, verbose_name='Источник (вставьте текст)')),
                ('assignment_type', models.CharField(choices=[('test', 'Тест (множественный выбор)'), ('fill', 'Заполнить пропуски'), ('theory', 'Теория / чтение')], max_length=20, verbose_name='Тип задания')),
                ('generated', models.JSONField(blank=True, default=dict, verbose_name='Сгенерированные вопросы/данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
