# Generated by Django 5.0 on 2026-07-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='theory_text',
            field=models.TextField(blank=True, verbose_name='Теория урока'),
        ),
        migrations.AddField(
            model_name='submission',
            name='answer_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ответы на задание'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('test', 'Тест (множественный выбор)'), ('fill', 'Заполнить пропуски'), ('short', 'Краткий ответ'), ('theory', 'Теория / чтение')], max_length=20, verbose_name='Тип задания'),
        ),
    ]
