# Generated by Django 5.0 on 2026-07-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_assignment_options_assignment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('rutube', 'Rutube'), ('upload', 'Файл')], max_length=10, verbose_name='Источник видео'),
        ),
    ]
